# Generated by Django 3.0.3 on 2020-04-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=64)),
                ('regtime', models.DateTimeField(auto_now_add=True)),
                ('logintime', models.DateTimeField(auto_now=True)),
                ('classes', models.CharField(default='', max_length=64)),
                ('number', models.CharField(default='', max_length=64)),
                ('qq', models.CharField(default='', max_length=20, null=True)),
                ('email', models.CharField(default='', max_length=64, null=True)),
                ('type', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('ac_number', models.IntegerField(default=0)),
                ('submit_number', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=1500)),
                ('ac_problem', models.TextField(default='', null=True)),
            ],
            options={
                'db_table': 'user_data',
                'ordering': ('-rating',),
            },
        ),
    ]
