# Generated by Django 3.0.3 on 2020-05-28 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=64)),
                ('regtime', models.DateTimeField(auto_now_add=True)),
                ('logintime', models.DateTimeField(auto_now=True)),
                ('classes', models.CharField(default='', max_length=64)),
                ('number', models.CharField(default='', max_length=64)),
                ('qq', models.CharField(default='', max_length=20, null=True)),
                ('email', models.CharField(default='', max_length=64, null=True)),
                ('type', models.CharField(default='Regular User', max_length=64)),
                ('ac_number', models.IntegerField(default=0)),
                ('submit_number', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=1500)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserLoginData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('ip', models.CharField(default='unknown', max_length=150, null=True)),
                ('logintime', models.DateTimeField(auto_now=True)),
                ('msg', models.TextField(null=True)),
            ],
            options={
                'db_table': 'user_login_data',
                'ordering': ('-logintime',),
            },
        ),
        migrations.CreateModel(
            name='UserACProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'user_ac_problem',
            },
        ),
    ]
