# Generated by Django 3.0.3 on 2020-05-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openlanguage', models.CharField(default='C++|C|Python|Java', max_length=500)),
                ('openoi', models.BooleanField(default=True)),
                ('openstatus', models.BooleanField(default=True)),
                ('openvisitor', models.BooleanField(default=True)),
                ('openregister', models.BooleanField(default=True)),
                ('openselfstatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'setting_board',
            },
        ),
    ]
