# Generated by Django 3.0.3 on 2020-04-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problemid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('author', models.CharField(default='eric_xie', max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('addtime', models.DateTimeField(auto_now=True)),
                ('problemdes', models.TextField()),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('sinput', models.TextField()),
                ('soutput', models.TextField()),
                ('source', models.TextField(null=True)),
                ('time', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('hint', models.TextField(null=True)),
                ('auth', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProblemData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemid', models.CharField(max_length=64)),
                ('level', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('submission', models.IntegerField()),
                ('acnum', models.IntegerField()),
                ('wanum', models.IntegerField()),
                ('mlenum', models.IntegerField()),
                ('renum', models.IntegerField()),
                ('cenum', models.IntegerField()),
                ('penum', models.IntegerField()),
                ('senum', models.IntegerField()),
                ('auth', models.IntegerField()),
                ('score', models.IntegerField()),
                ('tag', models.ManyToManyField(to='problem.ProblemTag')),
            ],
        ),
    ]
