# Generated by Django 3.0.3 on 2020-05-28 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problem_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('level', models.CharField(default='Medium', max_length=64)),
                ('score', models.IntegerField(default=0)),
                ('addtime', models.DateTimeField(auto_now=True)),
                ('auth', models.CharField(default='Public', max_length=64)),
            ],
            options={
                'db_table': 'problem',
                'ordering': ('problem_id',),
            },
        ),
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField()),
            ],
            options={
                'db_table': 'problemtag',
            },
        ),
        migrations.CreateModel(
            name='ProblemDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=64, null=True)),
                ('problemdes', models.TextField()),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('sinput', models.TextField()),
                ('soutput', models.TextField()),
                ('source', models.TextField(null=True)),
                ('time', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('hint', models.TextField(null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem', unique=True)),
            ],
            options={
                'db_table': 'problem_detail',
                'ordering': ('problem',),
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='tag',
            field=models.ManyToManyField(to='problem.ProblemTag'),
        ),
    ]
