# Generated by Django 3.0.3 on 2020-04-25 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ('addtime',)},
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='problemid',
            new_name='problem_id',
        ),
        migrations.RenameField(
            model_name='problemdata',
            old_name='problemid',
            new_name='problem_id',
        ),
        migrations.AddField(
            model_name='problem',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Contest'),
        ),
        migrations.AddField(
            model_name='problemdata',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Contest'),
        ),
        migrations.AlterModelTable(
            name='problem',
            table='problem',
        ),
        migrations.AlterModelTable(
            name='problemdata',
            table='problem_data',
        ),
        migrations.AlterModelTable(
            name='problemtag',
            table='problem_tag',
        ),
    ]
