# Generated by Django 3.0.3 on 2020-05-29 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestproblem',
            old_name='contest_id',
            new_name='contest',
        ),
        migrations.RenameField(
            model_name='contestproblem',
            old_name='problem_id',
            new_name='problem',
        ),
    ]
