# Generated by Django 3.0.3 on 2020-05-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20200529_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acmcontestrank',
            name='total_time',
            field=models.IntegerField(default=0),
        ),
    ]
