# Generated by Django 3.0.3 on 2020-05-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_contestparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='acmcontestrank',
            name='ac_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='oicontestrank',
            name='submit_time',
            field=models.IntegerField(default=0),
        ),
    ]
