# Generated by Django 3.0.3 on 2020-05-31 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casestatus',
            old_name='status_id',
            new_name='status',
        ),
    ]
