# Generated by Django 3.0.3 on 2020-06-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_auto_20200531_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quicktest',
            name='memory',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quicktest',
            name='message',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='quicktest',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='status',
            name='judger',
            field=models.CharField(default='judger', max_length=64),
        ),
        migrations.AlterField(
            model_name='status',
            name='memory',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='status',
            name='message',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='status',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
